import { useState } from "react";
import { useSkillStore } from "../stores/skillStore";
import { useToast, EmptyState, Modal } from "../components/ui";
import type { Skill } from "../types";

export default function SkillsPage() {
  const { skills, addSkill, updateSkill, deleteSkill, searchQuery, setSearchQuery, filterCategory, setFilterCategory, getFilteredSkills, incrementUsage } = useSkillStore();
  const { addToast } = useToast();

  const [showAddModal, setShowAddModal] = useState(false);
  const [editingSkill, setEditingSkill] = useState<Skill | null>(null);
  const [previewSkill, setPreviewSkill] = useState<Skill | null>(null);
  const [newSkill, setNewSkill] = useState({ name: "", description: "", category: "autre" as Skill["category"], content: "", tags: "" });

  const filteredSkills = getFilteredSkills();
  const categories = ["all", "devops", "dev", "data", "media", "adhd", "autre"];

  const handleAddSkill = () => {
    if (!newSkill.name.trim() || !newSkill.content.trim()) {
      addToast({ type: "error", message: "Nom et contenu requis" });
      return;
    }
    addSkill({
      id: crypto.randomUUID(),
      name: newSkill.name.trim(),
      description: newSkill.description.trim(),
      category: newSkill.category,
      content: newSkill.content.trim(),
      tags: newSkill.tags.split(",").map(t => t.trim()).filter(Boolean),
      createdAt: Date.now(),
      updatedAt: Date.now(),
      usageCount: 0,
      autoGenerated: false,
    });
    setNewSkill({ name: "", description: "", category: "autre", content: "", tags: "" });
    setShowAddModal(false);
    addToast({ type: "success", message: `Skill "${newSkill.name}" créé` });
  };

  const handleUpdateSkill = () => {
    if (!editingSkill) return;
    updateSkill(editingSkill.id, {
      name: editingSkill.name,
      description: editingSkill.description,
      content: editingSkill.content,
      category: editingSkill.category,
      tags: editingSkill.tags,
    });
    setEditingSkill(null);
    addToast({ type: "success", message: "Skill mis à jour" });
  };

  const handleDeleteSkill = (id: string) => {
    deleteSkill(id);
    addToast({ type: "info", message: "Skill supprimé" });
  };

  const handleUseSkill = (skill: Skill) => {
    incrementUsage(skill.id);
    setPreviewSkill(skill);
  };

  return (
    <div className="page">
      <div className="page-header">
        <h2>✨ Skills ({skills.length})</h2>
        <div className="page-actions">
          <input
            type="text"
            className="search-input"
            placeholder="🔍 Rechercher un skill..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
          />
          <select
            className="filter-select"
            value={filterCategory}
            onChange={(e) => setFilterCategory(e.target.value)}
          >
            {categories.map(c => (
              <option key={c} value={c}>{c === "all" ? "Toutes" : c}</option>
            ))}
          </select>
          <button className="btn btn-primary btn-sm" onClick={() => setShowAddModal(true)}>
            + Créer
          </button>
        </div>
      </div>

      <div className="skills-grid">
        {filteredSkills.length === 0 && (
          <EmptyState icon="✨" title="Aucun skill" subtitle="Créez votre premier skill ou laissez l'IA en générer automatiquement" />
        )}
        {filteredSkills.map((skill) => (
          <div key={skill.id} className={`skill-card ${skill.autoGenerated ? 'auto-generated' : ''}`}>
            <div className="skill-card-header">
              <div>
                <h4>{skill.autoGenerated ? '🤖' : '✨'} {skill.name}</h4>
                <span className="skill-category">{skill.category}</span>
              </div>
              <div className="skill-card-actions">
                <button className="btn btn-xs btn-secondary" onClick={() => handleUseSkill(skill)}>📖 Voir</button>
                <button className="btn btn-xs btn-secondary" onClick={() => setEditingSkill({ ...skill })}>✏️</button>
                <button className="btn btn-xs btn-danger" onClick={() => handleDeleteSkill(skill.id)}>🗑️</button>
              </div>
            </div>
            <p className="skill-desc">{skill.description}</p>
            {skill.tags.length > 0 && (
              <div className="skill-tags">
                {skill.tags.map(tag => (
                  <span key={tag} className="tag-chip small">#{tag}</span>
                ))}
              </div>
            )}
            <div className="skill-meta">
              <span>Utilisé {skill.usageCount}x</span>
              <span>{new Date(skill.updatedAt).toLocaleDateString("fr-FR")}</span>
            </div>
          </div>
        ))}
      </div>

      {/* Add Modal */}
      <Modal isOpen={showAddModal} onClose={() => setShowAddModal(false)} title="Créer un skill" size="lg">
        <div className="form-group">
          <label>Nom</label>
          <input type="text" placeholder="ex: docker-deploy" value={newSkill.name}
            onChange={(e) => setNewSkill({ ...newSkill, name: e.target.value })} />
        </div>
        <div className="form-group">
          <label>Description</label>
          <input type="text" placeholder="Description courte" value={newSkill.description}
            onChange={(e) => setNewSkill({ ...newSkill, description: e.target.value })} />
        </div>
        <div className="form-group">
          <label>Catégorie</label>
          <select value={newSkill.category} onChange={(e) => setNewSkill({ ...newSkill, category: e.target.value as Skill["category"] })}>
            <option value="devops">DevOps</option>
            <option value="dev">Dev</option>
            <option value="data">Data</option>
            <option value="media">Media</option>
            <option value="adhd">ADHD</option>
            <option value="autre">Autre</option>
          </select>
        </div>
        <div className="form-group">
          <label>Contenu Markdown</label>
          <textarea rows={8} placeholder="---&#10;name: skill-name&#10;description: ...&#10;---&#10;&#10;# Skill Name&#10;..." value={newSkill.content}
            onChange={(e) => setNewSkill({ ...newSkill, content: e.target.value })} />
        </div>
        <div className="form-group">
          <label>Tags (séparés par virgules)</label>
          <input type="text" placeholder="ex: docker, deploy, vps" value={newSkill.tags}
            onChange={(e) => setNewSkill({ ...newSkill, tags: e.target.value })} />
        </div>
        <div className="modal-actions">
          <button className="btn btn-secondary" onClick={() => setShowAddModal(false)}>Annuler</button>
          <button className="btn btn-primary" onClick={handleAddSkill}>Créer</button>
        </div>
      </Modal>

      {/* Edit Modal */}
      {editingSkill && (
        <Modal isOpen={true} onClose={() => setEditingSkill(null)} title="Modifier le skill" size="lg">
          <div className="form-group">
            <label>Nom</label>
            <input type="text" value={editingSkill.name}
              onChange={(e) => setEditingSkill({ ...editingSkill, name: e.target.value })} />
          </div>
          <div className="form-group">
            <label>Description</label>
            <input type="text" value={editingSkill.description}
              onChange={(e) => setEditingSkill({ ...editingSkill, description: e.target.value })} />
          </div>
          <div className="form-group">
            <label>Contenu Markdown</label>
            <textarea rows={12} value={editingSkill.content}
              onChange={(e) => setEditingSkill({ ...editingSkill, content: e.target.value })} />
          </div>
          <div className="modal-actions">
            <button className="btn btn-secondary" onClick={() => setEditingSkill(null)}>Annuler</button>
            <button className="btn btn-primary" onClick={handleUpdateSkill}>Enregistrer</button>
          </div>
        </Modal>
      )}

      {/* Preview Modal */}
      {previewSkill && (
        <Modal isOpen={true} onClose={() => setPreviewSkill(null)} title={`📖 ${previewSkill.name}`} size="lg">
          <div className="skill-preview">
            <div className="skill-preview-header">
              <span className="skill-category">{previewSkill.category}</span>
              {previewSkill.autoGenerated && <span className="badge badge-auto">🤖 Auto-généré</span>}
            </div>
            <pre className="skill-markdown">{previewSkill.content}</pre>
          </div>
          <div className="modal-actions">
            <button className="btn btn-secondary" onClick={() => setPreviewSkill(null)}>Fermer</button>
          </div>
        </Modal>
      )}
    </div>
  );
}
