import { create } from 'zustand';
import { persist, createJSONStorage } from 'zustand/middleware';
import type { Skill } from '../types';

interface SkillState {
  skills: Skill[];
  activeSkillId: string | null;
  searchQuery: string;
  filterCategory: string;

  // CRUD
  addSkill: (skill: Skill) => void;
  updateSkill: (id: string, updates: Partial<Skill>) => void;
  deleteSkill: (id: string) => void;
  getSkill: (id: string) => Skill | undefined;

  // Auto-create from task
  createSkillFromTask: (taskName: string, steps: string[], category: Skill['category']) => Skill;

  // Search & filter
  setSearchQuery: (query: string) => void;
  setFilterCategory: (category: string) => void;
  getFilteredSkills: () => Skill[];

  // Stats
  incrementUsage: (id: string) => void;
  getTopSkills: (limit?: number) => Skill[];
}

export const useSkillStore = create<SkillState>()(
  persist(
    (set, get) => ({
      skills: [],
      activeSkillId: null,
      searchQuery: '',
      filterCategory: 'all',

      addSkill: (skill) =>
        set((state) => ({ skills: [skill, ...state.skills] })),

      updateSkill: (id, updates) =>
        set((state) => ({
          skills: state.skills.map((s) =>
            s.id === id ? { ...s, ...updates, updatedAt: Date.now() } : s
          ),
        })),

      deleteSkill: (id) =>
        set((state) => ({
          skills: state.skills.filter((s) => s.id !== id),
          activeSkillId: state.activeSkillId === id ? null : state.activeSkillId,
        })),

      getSkill: (id) => get().skills.find((s) => s.id === id),

      createSkillFromTask: (taskName, steps, category) => {
        const now = Date.now();
        const id = crypto.randomUUID();
        const kebabName = taskName
          .toLowerCase()
          .replace(/[^a-z0-9]+/g, '-')
          .replace(/^-|-$/g, '');

        const skill: Skill = {
          id,
          name: kebabName,
          description: `Skill auto-généré pour: ${taskName}`,
          category,
          content: `---
name: ${kebabName}
description: Skill auto-généré pour ${taskName}
category: ${category}
auto-generated: true
---

# ${taskName}

## Description
Skill créé automatiquement après la résolution réussie de cette tâche.

## Quand l'utiliser
- Quand l'utilisateur demande: ${taskName}
- Contexte similaire à la tâche originale

## Étapes
${steps.map((s, i) => `${i + 1}. ${s}`).join('\n')}

## Résultat attendu
- Tâche complétée avec succès
- Pas d'erreurs

## Erreurs connues
- À remplir après utilisation

## Notes
- Auto-généré le ${new Date(now).toLocaleDateString('fr-FR')}
- À améliorer avec l'expérience
`,
          tags: kebabName.split('-'),
          createdAt: now,
          updatedAt: now,
          usageCount: 0,
          autoGenerated: true,
        };

        get().addSkill(skill);
        return skill;
      },

      setSearchQuery: (query) => set({ searchQuery: query }),
      setFilterCategory: (category) => set({ filterCategory: category }),

      getFilteredSkills: () => {
        const { skills, searchQuery, filterCategory } = get();
        return skills.filter((s) => {
          const matchesSearch =
            !searchQuery ||
            s.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
            s.description.toLowerCase().includes(searchQuery.toLowerCase()) ||
            s.tags.some((t) => t.toLowerCase().includes(searchQuery.toLowerCase()));
          const matchesCategory = filterCategory === 'all' || s.category === filterCategory;
          return matchesSearch && matchesCategory;
        });
      },

      incrementUsage: (id) =>
        set((state) => ({
          skills: state.skills.map((s) =>
            s.id === id ? { ...s, usageCount: s.usageCount + 1 } : s
          ),
        })),

      getTopSkills: (limit = 5) => {
        return [...get().skills]
          .sort((a, b) => b.usageCount - a.usageCount)
          .slice(0, limit);
      },
    }),
    {
      name: 'seb-atlantis-skills-v4',
      storage: createJSONStorage(() => localStorage),
      version: 4,
    }
  )
);
